**Contents**

- review class
- review loop + dictionary
- try except
- assert
- csv, json, centext manager
- web scraping
- numpy pandas sqlite sklearn

In [ ]:
# super class
class Person:
    def __init__(self, name):
        self.name = name
    def hey(self):
            print("hello world")
    def sayhi(self):
            print(f"Hi my name is {self.name}!")

class Employee(Person):
    def __init__(self, name, company):
        super().__init__(name)
        self.company = company
    def potato(self):
            print("Potato is very good!")
    def sayhi(self):
            print(f"Hi my name is {self.name} and I work at {self.company}.")


In [ ]:
toy = Person("Toy")
john = Employee("John", "Google")
toy.sayhi()
john.sayhi()

Hi my name is Toy!
Hi my name is John and I work at Google.


In [ ]:
toy.hey()

hello world


In [ ]:
john.sayhi()
john.potato()

Hi my name is John and I work at Google.
Potato is very good!


In [ ]:
# try-except block
try :
        print("hello")
except ZeroDivisionError:
        print("Cannot divide a number with zero")
except NameError:
        print("Variable is not found.")
except ValueError:
        print("Please check your data type again")
else:
        print("Done!")
finally:
        print("This is the last line.")

hello
Done!
This is the last line.


In [ ]:
x = 10

In [ ]:
assert 1+1 == 5, "1+1 must be equal 2"

AssertionError: ignored

In [ ]:
#tyoe hint
def check_this(a: int, b: int) -> int:
    assert a+b > 10, "a+b should be more than ten"
    return a+b

In [ ]:
check_this(5,6)

11

In [ ]:
def greeting(name):
        print("hello! " + name)

In [ ]:
greeting = lambda name: print("hello! " + name)

In [ ]:
greeting("toy")

hello! toy


In [ ]:
def odd_or_even(num):
        if num % 2 == 0:
                print("Even")
        else:
                print("Odd")

In [ ]:
#ส่งค่า Even กลับมาถ้า num % 2 = 0
#lambda simple function
odd_or_even = lambda num: "even" if num % 2 == 0 else "odd"

In [ ]:
odd_or_even(6)

'even'

In [ ]:
# review class
# try except
# assert 1+1 == 2, "error message"
# lambda function

In [ ]:
hello = lambda : print("hello!")

In [ ]:
hello()

hello!


In [ ]:
# list of conlored balls
balls = ['red', 'red', 'green','green', 'blue','blue']

In [ ]:
{
    'red': 2, 'green':1, 'blue':
}

{'red': 2, 'green': 1, 'blue': 2}

In [ ]:
def summary(lst_items):
    result = {} # empty dict
    for item in lst_items:
        if item in result:
            result[item] += 1
        else:
            result[item] = 1
    return(result)

In [ ]:
summary(balls)

{'red': 2, 'green': 2, 'blue': 2}

In [ ]:
# read CSV flie
# comma separated values (CSV flie)

In [ ]:
!ls sample_data

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
!mkdir newFolder

In [ ]:
!rmdir newFolder

In [ ]:
!echo hello

hello


In [ ]:
!cat hotel.csv

id,hotel,location,price
1,Accor,Thailand,50
2,Ibis,Italy,60
3,London,UK,35
4,Seoul,Korea,30
5,le Concord,USA,25


In [ ]:
import csv # module

try:
    file = open("hotel.csv")
    data = csv.reader(file)
    file.close()
except FileNotFoundError:
    print("File not found.")
else:
    print("Load data successfully.")

Load data successfully.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

In [ ]:
# context manager
import csv

try:
    with open("hotel.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
          print(row)
except:
    print("Found some errors, please check again.")

['id', 'hotel', 'location', 'price']
['1', 'Accor', 'Thailand', '50']
['2', 'Ibis', 'Italy', '60']
['3', 'London', 'UK', '35']
['4', 'Seoul', 'Korea', '30']
['5', 'le Concord', 'USA', '25']


In [ ]:
# context manager
csv_data = [] # empty list

with open("hotel.csv") as file:
    data = csv.reader(file)
    for row in data:
        csv_data.append(row)

print(csv_data)

[['id', 'hotel', 'location', 'price'], ['1', 'Accor', 'Thailand', '50'], ['2', 'Ibis', 'Italy', '60'], ['3', 'London', 'UK', '35'], ['4', 'Seoul', 'Korea', '30'], ['5', 'le Concord', 'USA', '25']]


In [ ]:
import pandas as pd

df = pd.read_csv("hotel.csv")

df

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  le Concord       USA     25

In [ ]:
# write csv file modern pandas
import pandas as pd

df = pd.read_csv("hotel.csv")

df["price_double"] = df["price"]*2

df.to_csv("hotel_modified.csv") # export file

In [ ]:
!cat hotel_modified.csv

,id,hotel,location,price,price_double
0,1,Accor,Thailand,50,100
1,2,Ibis,Italy,60,120
2,3,London,UK,35,70
3,4,Seoul,Korea,30,60
4,5,le Concord,USA,25,50


In [ ]:
# write csv file 2
#"w" = write mode
import csv

headers = ["id", "name", "age"]
data = [
    [1, "toy", 25],
    [2, "jisoo", 26],
    [3, "john", 32]
]

with open("newfile.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(headers)
    writer.writerows(data)

In [ ]:
!cat newfile.csv

id,name,age
1,toy,25
2,jisoo,26
3,john,32


In [ ]:
result = []
with open("newfile.csv", "r") as file:
    data = csv.reader(file)
    for row in data:
        result.append(row)
print(result)


[['id', 'name', 'age'], ['1', 'toy', '25'], ['2', 'jisoo', '26'], ['3', 'john', '32']]


In [ ]:
# regular expression

import re
#from re import search

text = "a duck walks into a bar duck"

result = re.search("duck", text)

if result:
    print("Duck found")
else:
    print("Duck not found")


Duck found


In [ ]:
# list comprehension
numbers = [1,2,3,4,5] # => [2,4]

In [ ]:
result = [num*2  for num in numbers]
print(result)

[2, 4, 6, 8, 10]


In [ ]:
oddNums = [num for num in numbers if num%2 == 1]
evenNums = [num for num in numbers if num%2 == 0]

print(oddNums, evenNums)

[1, 3, 5] [2, 4]


In [ ]:
## json => JavaScript Object Notation
!ls *.json

'toy json.json'   toy.json.json


In [ ]:
import json

with open("toy.json", "r") as file:
    data = json.load(file)

In [ ]:
data

{'name': 'toy',
 'age': 34,
 'movie_lover': True,
 'movies': ['batman', 'superman']}

In [ ]:
#check type
print(data, type(data))

{'name': 'toy', 'age': 34, 'movie_lover': True, 'movies': ['batman', 'superman']} <class 'dict'>


In [ ]:
data["age"]

34

In [ ]:
data["movies"][1]

'superman'

In [ ]:
# create new .json file
school = {
    "name": "bootcamp",
    "batch": 7,
    "duration": "4 months"
}
with open("newjsofile.json", "w") as file:
    json.dump(school, file)

In [ ]:
!cat newjsofile.json

{"name": "bootcamp", "batch": 7, "duration": "4 months"}

In [ ]:
with open("newjsofile.json", "r") as file:
        data2 = json.load(file)

data2

{'name': 'bootcamp', 'batch': 7, 'duration': '4 months'}

In [ ]:
#API get request
import requests

url = "https://swapi.dev/api/people/1"

result = requests.get(url)

data_json = result.json()

data_json["name"]

'Luke Skywalker'

In [ ]:
import requests

url = "https://swapi.dev/api/people/9"

result = requests.get(url)

data_json = result.json()

data_json["mass"]

'84'

In [ ]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
#API get request
from requests import get
from time import sleep

nums = list(range(1,6))
result = []

for i in nums:
    url = f"https://swapi.dev/api/people/{i}"
    response = get(url)
    data = response.json()
    row = [
        data["name"],
        data["height"],
        data["mass"],
        data["gender"]
    ]
    result.append(row)
    print(result)
    sleep(1) # second

[['Luke Skywalker', '172', '77', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male']]
[['Luke Skywalker', '172', '77', 'male'], ['C-3PO', '167', '75', 'n/a'], ['R2-D2', '96', '32', 'n/a'], ['Darth Vader', '202', '136', 'male'], ['Leia Organa', '150', '49', 'female']]


In [ ]:
import pandas as pd

df = pd.DataFrame(result, columns =["name", "height", "mass", "gender"])

df.to_csv("starwarapi.csv")

In [ ]:
# web scraping
# gazpacho
!pip install gazpacho

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7480 sha256=52e6eb224ab9cfa1eb5ea46724c80db2a799e69fe1b8088822bd226e74dfa43e
  Stored in directory: /root/.cache/pip/wheels/7b/82/22/0f73f5a5fa5abb29aac7a06941ff561e0bb415e558bb64d467
Successfully built gazpacho


In [ ]:
!pip list | grep "^gaz"

gazpacho                      1.1


In [ ]:
from gazpacho import Soup
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

response = get(url)

imdb = Soup(response.text)

In [ ]:
#strip ใช้ในการลบอักขระพิเศษ
imdb.find("h3")[0].strip()

'1. The Shawshank Redemption (1994)'

In [ ]:
#กรณีเป็นภาษาจีนใช้ header ช่วย
from gazpacho import Soup
from requests import get

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"
headers = {"Accept-Language":"en-US"}

response = get(url)

imdb = Soup(response.text)

In [ ]:
imdb.find("h3")[9].strip()

'10. The Lord of the Rings: The Fellowship of the Ring (2001)'

In [ ]:
title_list = imdb.find("h3",{"class": "lister-item-header"})

In [ ]:
for title in title_list:
    print(title.strip())

1. The Shawshank Redemption (1994)
2. The Godfather (1972)
3. The Dark Knight (2008)
4. Schindler's List (1993)
5. The Lord of the Rings: The Return of the King (2003)
6. De 12 gezworenen (1957)
7. The Godfather Part II (1974)
8. Pulp Fiction (1994)
9. Inception (2010)
10. The Lord of the Rings: The Fellowship of the Ring (2001)
11. Fight Club (1999)
12. Forrest Gump (1994)
13. The Good, the Bad and the Ugly (1966)
14. The Lord of the Rings: The Two Towers (2002)
15. The Matrix (1999)
16. Goodfellas (1990)
17. One Flew Over the Cuckoo's Nest (1975)
18. Star Wars: Episode V - The Empire Strikes Back (1980)
19. Interstellar (2014)
20. De sterrenoorlogen (1977)
21. Seven (1995)
22. The Silence of the Lambs (1991)
23. The Green Mile (1999)
24. Spirited Away: De reis van Chihiro (2001)
25. Terminator 2: Judgment Day (1991)
26. Saving Private Ryan (1998)
27. Cidade de Deus (2002)
28. Het leven is mooi (1997)
29. Shichinin no samurai (1954)
30. It's a Wonderful Life (1946)
31. Seppuku (1962)


In [ ]:
titles = [title.strip() for title in title_list]
print(titles)

['1. The Shawshank Redemption (1994)', '2. The Godfather (1972)', '3. The Dark Knight (2008)', "4. Schindler's List (1993)", '5. The Lord of the Rings: The Return of the King (2003)', '6. De 12 gezworenen (1957)', '7. The Godfather Part II (1974)', '8. Pulp Fiction (1994)', '9. Inception (2010)', '10. The Lord of the Rings: The Fellowship of the Ring (2001)', '11. Fight Club (1999)', '12. Forrest Gump (1994)', '13. The Good, the Bad and the Ugly (1966)', '14. The Lord of the Rings: The Two Towers (2002)', '15. The Matrix (1999)', '16. Goodfellas (1990)', "17. One Flew Over the Cuckoo's Nest (1975)", '18. Star Wars: Episode V - The Empire Strikes Back (1980)', '19. Interstellar (2014)', '20. De sterrenoorlogen (1977)', '21. Seven (1995)', '22. The Silence of the Lambs (1991)', '23. The Green Mile (1999)', '24. Spirited Away: De reis van Chihiro (2001)', '25. Terminator 2: Judgment Day (1991)', '26. Saving Private Ryan (1998)', '27. Cidade de Deus (2002)', '28. Het leven is mooi (1997)',

In [ ]:
runtimes = imdb.find("span", {"class": "runtime"})
runtimes = [runtime.strip()for runtime in runtimes]
print(runtimes)

['142 min', '175 min', '152 min', '195 min', '201 min', '96 min', '202 min', '154 min', '148 min', '178 min', '139 min', '142 min', '161 min', '179 min', '136 min', '145 min', '133 min', '124 min', '169 min', '121 min', '127 min', '118 min', '189 min', '125 min', '137 min', '169 min', '130 min', '116 min', '207 min', '130 min', '133 min', '155 min', '106 min', '132 min', '151 min', '116 min', '102 min', '130 min', '109 min', '117 min', '147 min', '110 min', '150 min', '88 min', '106 min', '119 min', '112 min', '165 min', '89 min', '112 min']


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "title": titles,
    "runtime": runtimes
})

df.head()

title  runtime
0                 1. The Shawshank Redemption (1994)  142 min
1                            2. The Godfather (1972)  175 min
2                          3. The Dark Knight (2008)  152 min
3                         4. Schindler's List (1993)  195 min
4  5. The Lord of the Rings: The Return of the Ki...  201 min

In [ ]:
df.to_csv("imdb.csv")

# Basic Data Tools

- numpy
- pandas
- sklearn

In [ ]:
#numpy => numberical python
import numpy as np

num = [1,2,3,4,5]

num_arr = np.array(num)

In [ ]:
print(num_arr * 2, num_arr + 2, num_arr - 2, num_arr /5)

[ 2  4  6  8 10] [3 4 5 6 7] [-1  0  1  2  3] [0.2 0.4 0.6 0.8 1. ]


In [ ]:
#statistical basic calculation
np.sum(num_arr)
np.mean(num_arr)
np.std(num_arr)
np.min(num_arr)
np.max(num_arr)
len(num_arr)

5

In [ ]:
#ใช้ method ได้บางฟังก์ชัน
num_arr.sum()

15

In [ ]:
#ถ้าเป็น median จะยังใช้ไม่ได้
np.median(num_arr)

3.0

In [ ]:
#matrix 2D-array
m1 = np.array([
    [1,2],
    [3,4]
])

In [ ]:
m2 = np.array([
    [5, 5],
    [4, 2]
])

In [ ]:
print(m1, "\n"*2, m2)

[[1 2]
 [3 4]] 

 [[5 5]
 [4 2]]


In [ ]:
#m1.dot(m2)
np.dot(m1, m2)

array([[13,  9],
       [31, 23]])

In [ ]:
# intro to pandas

import pandas as pd
import numpy as np

In [ ]:
hotel = pd.read_csv("hotel.csv")

In [ ]:
hotel.shape # (row, col)

(5, 4)

In [ ]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        5 non-null      int64 
 1   hotel     5 non-null      object
 2   location  5 non-null      object
 3   price     5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes


In [ ]:
hotel.describe(include="all")

id  hotel  location     price
count   5.000000      5         5   5.00000
unique       NaN      5         5       NaN
top          NaN  Accor  Thailand       NaN
freq         NaN      1         1       NaN
mean    3.000000    NaN       NaN  40.00000
std     1.581139    NaN       NaN  14.57738
min     1.000000    NaN       NaN  25.00000
25%     2.000000    NaN       NaN  30.00000
50%     3.000000    NaN       NaN  35.00000
75%     4.000000    NaN       NaN  50.00000
max     5.000000    NaN       NaN  60.00000

In [ ]:
# วิธีดึงแบบที่ 1 hotel["location"]
hotel["location"]

0    Thailand
1       Italy
2          UK
3       Korea
4         USA
Name: location, dtype: object

In [ ]:
#แบบที่ 2
hotel.location

0    Thailand
1       Italy
2          UK
3       Korea
4         USA
Name: location, dtype: object

In [ ]:
hotel["vat"] = hotel["price"] * 0.07
# r version
# hotel$vat <- hotel$price * 0.07
hotel

id       hotel  location  price   vat
0   1       Accor  Thailand     50  3.50
1   2        Ibis     Italy     60  4.20
2   3      London        UK     35  2.45
3   4       Seoul     Korea     30  2.10
4   5  le Concord       USA     25  1.75

In [ ]:
# query (filter rows)
hotel.query( "price > 40" )

#r version
# filter(hotel, price > 40)

id  hotel  location  price  vat
0   1  Accor  Thailand     50  3.5
1   2   Ibis     Italy     60  4.2

In [ ]:
value_hotel = hotel.query("price < = 40")
value_hotel.to_csv("value_hotel.csv")

In [ ]:
# drop column
hotel.drop(["id","vat"], axis=1)

hotel  location  price
0       Accor  Thailand     50
1        Ibis     Italy     60
2      London        UK     35
3       Seoul     Korea     30
4  le Concord       USA     25

In [ ]:
new_hotel = hotel.drop(["id","vat"], axis=1)
new_hotel

hotel  location  price
0       Accor  Thailand     50
1        Ibis     Italy     60
2      London        UK     35
3       Seoul     Korea     30
4  le Concord       USA     25

In [ ]:
#ใช้ inplace สามารถลบได้เลย ไม่ต้อง assign ค่ากลับไป
#hotel = hotel.drop("vat", axis=1)
hotel.drop("vat", axis=1, inplace=True)
hotel

id       hotel  location  price
0   1       Accor  Thailand     50
1   2        Ibis     Italy     60
2   3      London        UK     35
3   4       Seoul     Korea     30
4   5  le Concord       USA     25

In [ ]:
hotel

hotel  location  price
0       Accor  Thailand     50
1        Ibis     Italy     60
2      London        UK     35
3       Seoul     Korea     30
4  le Concord       USA     25

In [ ]:
hotel.query(" price < 40 and location  == 'UK' ")

hotel location  price
2  London       UK     35

In [ ]:
hotel.query(" price > 30 or location  == 'UK' ")

hotel  location  price
0   Accor  Thailand     50
1    Ibis     Italy     60
2  London        UK     35

In [ ]:
# sklearn => machine learning most popular python
# template in sklearn to train_test_split

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pandas as pd

In [ ]:
mtcars = pd.read_csv("https://gist.github.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")

In [ ]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
# prepare 50-80%
# mpg = f(hp,wt,am)
X = mtcars[ ["hp", "wt", "am"] ]
y = mtcars[ "mpg" ]

In [ ]:
# split data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
#train model
#เขียนย่อ model = LinearRegression().fit(X_train, y_train)
#model = LinearRegression()
#model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(X_train, y_train)

# test model/ scoring
pred = model.predict(X_test)

# MAE mean absolute error
mae = np.mean(np.absolute((y_test - pred)))

# MSE
mse = np.mean((y_test - pred)**2)

print(mae, mse)

2.2267142857142854 9.198073571428534


In [ ]:
# r caret
model = train(y ~ x, data, method="lm")

p = predict(model, newdata)

# calculate MAE, MSE, RMSE

SyntaxError: ignored